### ISSUE TITLE
Navigation links are announced twice by screen readers

### ISSUE THREAD

**Issue by scottaohara** [ua-oira/oira.ua.edu#1]
# Issue:
In the primary navigation of the website, each link has a `title` attribute with a duplicate value of the visible link text.

This results in some screen readers, such as Apple's VoiceOver, reading the text of the link, and then repeating the same text again. 

For example, when navigating to the mission link, VoiceOver announces the following:
"Link Mission. Mission, You are currently on a link..."

# Fix:
Remove the `title` attribute from these links, and any other links, where the value of the attribute is the same as the visible text of the link.

**Comment by coston** [comment]
Legit! Thank you @scottaohara!! 🙌🏻✨

**Comment by scottaohara** [comment]
Looks like Factbook still has a `title` set. But super turnaround time :D

**Comment by coston** [comment]
Ah! Thanks! Removed that one as well now. 🙃
